# Generated by Django 3.1.6 on 2021-03-16 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre: ')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido: ')),
                ('descripcion', models.TextField()),
                ('fechaReg', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro: ')),
                ('edad', models.PositiveIntegerField(default=0)),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Empleado',
                'db_table': 'Empleado',
                'ordering': ['id'],
            },
        ),
    ]
